#!/bin/bash

# @author Trey Rubino

ROOT_DIR="$(dirname "$0")/.."
REF_DIR="$ROOT_DIR/reference"
TEST_DIR="$ROOT_DIR/test/cool-examples"
REPORT="$ROOT_DIR/scripts/delta.txt"

rm -f "$REPORT"

echo "Reference vs. Hand-rolled Delta Report" >> "$REPORT"
echo "Generated on $(date)" >> "$REPORT"
echo "Generated by Trey Rubino" >> "$REPORT"
echo "-------------------------------------------------------------------" >> "$REPORT"

shopt -s nullglob

names=()
for f in "$TEST_DIR"/*.cl-lex "$TEST_DIR"/*.cl-ast "$TEST_DIR"/*.cl-type; do
  [[ -f "$f" ]] || continue
  base="$(basename "$f")"
  name="${base%%.cl-*}"
  skip=false
  for n in "${names[@]}"; do
    [[ "$n" == "$name" ]] && skip=true && break
  done
  $skip || names+=("$name")
done

IFS=$'\n' sorted_names=($(printf '%s\n' "${names[@]}" | sort))
unset IFS

for name in "${sorted_names[@]}"; do    echo "$name" 
    echo "Delta File Group: $name" >> "$REPORT"
    echo "-------------------------------------------------------------------" >> "$REPORT"

    for ext in cl-lex cl-ast cl-type; do
        test_file="$TEST_DIR/$name.$ext"
        ref_file="$REF_DIR/$name.$ext"
            echo "$name" 

        if [[ ! -f "$test_file" ]]; then
            echo "Missing generated: $test_file" >> "$REPORT"
            continue
        fi
        if [[ ! -f "$ref_file" ]]; then
            echo "Missing reference: $ref_file" >> "$REPORT"
            continue
        fi

        diff_out=$(diff -u "$ref_file" "$test_file")
        if [[ -z "$diff_out" ]]; then
            echo " $ext — Match" >> "$REPORT"
        else
            echo " =$ext — Differences found:" >> "$REPORT"
            echo "$diff_out" >> "$REPORT"
        fi
        echo "" >> "$REPORT"
    done

    echo "===================================================================" >> "$REPORT"
done